### ISSUE TITLE
Problem with sending files on Ubuntu

### ISSUE THREAD

**Issue by Sh3b0** [Sh3B0/pft#1]
###  Steps to reproduce
1. Run flask server on Linux machine.
2. Try to send a file after getting 'Connected' status

### Expected behavior
- File transfer starts.

### Actual behavior
- Getting the following error from browser console
```
Uncaught (in promise) DOMException: Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'
    at RTCDataChannel.send (https://webrtc.github.io/adapter/adapter-latest.js:1442:34)
    at FileReader.sendChunk (http://127.0.0.1:5000/static/js/sender.js:71:21)
```

### Operating System
- Ubuntu 20.04 LTS

### Browser
- Google Chrome 91.0.4472.164

**Comment by Sh3b0** [comment]
It seems that the problem was caused by firewall blocking packets.
